# Generated by Django 5.0.6 on 2024-06-22 23:21

from django.db import migrations, models
import json

def clean_data(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.all():
        # Clean ingredients
        if isinstance(recipe.ingredients, str):
            ingredients = [i.strip() for i in recipe.ingredients.split(',') if i.strip()]
        else:
            ingredients = recipe.ingredients if recipe.ingredients else []

        # Clean instructions
        if isinstance(recipe.instructions, str):
            instructions = [i.strip() for i in recipe.instructions.split(',') if i.strip()]
        else:
            instructions = recipe.instructions if recipe.instructions else []

        # Convert to valid JSON format
        recipe.ingredients = json.dumps(ingredients)
        recipe.instructions = json.dumps(instructions)
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_owner'),
    ]

    operations = [
        migrations.RunPython(clean_data),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
